### ISSUE TITLE
Logical switch missing from flight mode switches

### ISSUE THREAD

**Issue by ulfhedlund** [EdgeTX/edgetx-user-manual#1]
On the flight mode page "logical switch" is missing from the list of possible switches.

Suggested revised text:
"Switch: The trigger to enable that flight mode. It can be a switch, pot, telemetry, trim or logical switch."

**Comment by ulfhedlund** [comment]
On a side note: I wonder how a PR can be created, as suggested in the read.me? I can't find any documentation files to create a fork from... I have contributed some to edgetx translations but this documentation seems to work differently.

**Comment by phileville** [comment]
I manually made the change directly on Github - I used that change to test the sync.. Thanks for submitting.  Also, the repo is setup of by-directional syncing, so you can make PRs if you see other things that need to be tightened up.
