### ISSUE TITLE
Useful Logical Switch and Special Functions

### ISSUE THREAD

**Issue by n4t3y** [EdgeTX/edgetx-user-manual#10]
Hello, I've created a sample process for creating a low voltage warning which reads out the current voltage of the battery.

It seems quite long so can you please advise:
- Whether it is too newbie - i.e. outlining each step and how to do it, eg I have indicated that you navigate using the scroll wheel and then push it to select the element, should it be less wordy such as "navigate to X and select it"
- Number of screenshots is acceptable
- The description of the process is adequate
[Useful Logical Switches and Special Functions.docx](https://github.com/EdgeTX/edgetx-user-manual/files/10680878/Useful.Logical.Switches.and.Special.Functions.docx)

Because similar LS/SF processes are the same, if we can work out whether this is the way we should be documenting it then that will determine the standard for the processes moving forward

**Comment by phileville** [comment]
Thank you for your contribution.  
I think that we can write these articles based on a intermediate user level.  You should be able to say navigate to "x" and select "y".
I also think that you can tone down the number of screen shots.  Should be enough to follow along and highlight any tricky things.  But I think like for pop-ups, you can simple say, "select x from the pop-up menu.
I think the description of what you are trying to do any why is important and must be clear.  
I have added an example of how detailed I would recommend to make the How-To documents.  It is just a rough draft, so it still needs a little polish and corrections, but I think you can get my idea... This is the detail that I would do.
[How to Example.docx](https://github.com/EdgeTX/edgetx-user-manual/files/10710223/How.to.Example.docx)

**Comment by agnauck** [comment]
I can finish this HowTo and create a PR
