### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by RCdiy** [EdgeTX/edgetx-user-manual#15]
Congratulations and thank you for launching EdgeTx. 

My name is Rav, RCdiy, and have been away from the hobby for a number of years. 

I am thrilled with your user manual. This is what I wanted for OpenTx. Without getting into details let's just say I ended up doing my own manual on my website. I can see with EdgeTx that this won't be necessary for me. 

Unfortunately due to my health I am not offering to help at the moment. Let me get back into the hobby first. 

I don't think many know this but I took over hosting of the OpenTX University website. I just wanted to keep it alive as is available. I didn't do any work on it other than a few quick changes.

**Comment by phileville** [comment]
Hello Rav - Thank you for your postive feedback and nice comments. I am familiar with your OpenTX site as I referenced it several times as I put together the EdgeTX user guide (I even mentioned it in the contributers section of the user guide). Thank you for your efforts on it. If you decide later on that you would like to make some contributions, I would be happy to have your help!
