### ISSUE TITLE
I cant acces to manuals of gitbook

### ISSUE THREAD

**Issue by maiflaii** [EdgeTX/edgetx-user-manual#20]
Hi, im trying enter to https://app.gitbook.com/o/-MgQ7Ok46bXLbvoz_AeM/s/G9cXG2SsywqpT8oP5rLH/b-and-w-radios but always have the same result, unauthoriced acces, how can I acces to this manuals?
Thanks

**Comment by phileville** [comment]
Unfortunately, that is the link for editors - which is why you cannot access it.  Here is the public link: https://edgetx.gitbook.io/edgetx-user-manual/b-and-w-radios

I will update the page so that it is not directing people to the editor page anylonger.  Sorry for the confusion.
