### ISSUE TITLE
Spanish manual (Manual en español) v2.9

### ISSUE THREAD

**Issue by Robertomirax** [EdgeTX/edgetx-user-manual#21]
I am working on spanish translation of EdgeTX User Manual v2.9.
Estoy trabajando en la traducción al español del Manual de uso EdgeTX v2.9
https://github.com/Robertomirax/Edgetx-manual-del-usuario
https://robertomirax.gitbook.io/untitled/
Bienvenidas las consultas y sugerencias.

Roberto Domingues

**Comment by phileville** [comment]
Hello Roberto,

Sorry that I did not see this sooner. I have added your gitbook link to the main user manual page.  Thanks!
