### ISSUE TITLE
Translation of User Manual for Color Screen Radios into Russian

### ISSUE THREAD

**Issue by Zloyuzver** [EdgeTX/edgetx-user-manual#27]
Hello. I recently finished translating the User Manual for Color Screen Radios for EdgeTX v.2.9 into Russian. This translation is attached to this message.
[User Manual EdgeTX v.2.9 for Color Screen Radios (Rus).pdf](https://github.com/EdgeTX/edgetx-user-manual/files/13795069/User.Manual.EdgeTX.v.2.9.for.Color.Screen.Radios.Rus.pdf)

**Comment by phileville** [comment]
Thank you for the submission. I have added it to the Gitbook page. Thank you again!

Phil

**Comment by Zloyuzver** [comment]
> Thank you for the submission. I have added it to the Gitbook page. Thank you again!
> 
> Phil

I was glad to help. The only thing is, if it’s not difficult, instead of my nickname Zloyuzver, indicate my first and last name - Kerget Ruslan. 
Thanks in advance.

**Comment by phileville** [comment]
No problem, I have updated the user guide credit with your full name.

Kind Regards,
Phil

**Comment by Zloyuzver** [comment]
Thank you very much :)
