### ISSUE TITLE
Index and page numbers

### ISSUE THREAD

**Issue by dbigger-56** [EdgeTX/edgetx-user-manual#28]
First I want to congratulate everyone that contributed to this manual for Edge TX.  It has been great for setting up my radio and helping with TX.   Is a way to include a index and page numbers in the printed version of the manual to make it easier to find subjects?

**Comment by phileville** [comment]
Thanks for your positive feedback. Unfortunately, the manual is formatted to be used digitially and not printed out. I have not found an easy way to add a table of contents and page numbers (for the printed pages) without a lot of manual work.  Once the 2.10 version of the manual is released, I will look to see if I can figure something out.
