### ISSUE TITLE
Add translations button and automatic translate by browser language

### ISSUE THREAD

**Issue by KondratokGK** [EdgeTX/edgetx-user-manual#36]
May be use [crowdin](crowdin.com) or similar tool?

**Comment by phileville** [comment]
Text translations of the manual can be produced by Google Translate.  https://translate.google.com/?sl=auto&tl=ru&op=websites
However, it will not translate the screenshots. Therefore, we will rely on community members to translate the manual (with screenshots) and submit it via PDF which we will then add to the https://manual.edgetx.org/translated-user-manuals page.
