### ISSUE TITLE
Retired NOOB

### ISSUE THREAD

**Issue by Thumper5745** [EdgeTX/edgetx-user-manual#38]
The EdgeTX manual is very well organized and written. kudos to the contributors. 
my issues as a NOOB are:
1. There needs to be a more detailed explanation of each parameter and a use case for it. Eg. What is a “curve” and why?
2. There needs to be more use cases. Referring to utube contributors is unsatisfactory. Not their fault but they assume too much prior knowledge.  I’m trying to navigate an unfamiliar interface and they are using parameters without an explanation. The best I’ve seen so far is Captain Drone setting up a drone. More like this would be helpful. 

Your efforts would be well received by those of us who are trying to enter this hobby.

**Comment by phileville** [comment]
Thank you for your positive feedback. I agree, there is a big learning curve when starting out with EdgeTX.  The user manual is more focused on explaining what all the various settings do rather then cover all the use cases how to use them. Unfortunately, I think that it is beyond the scope of the User Manual right now to cover them all.  However, there is a very good website that DOES a great job explaining in great detail these things.  Please take a look as I am sure that you will find it helpful!  [https://rc-soar.com/edgetx/](https://rc-soar.com/edgetx/)
