### ISSUE TITLE
Contribution: Chinese Translation of the EdgeTX User Manual

### ISSUE THREAD

**Issue by zkl2333** [EdgeTX/edgetx-user-manual#48]
Hello,  

I am a beginner and not a professional RC player. Every time I read the official manual, I have to rely on machine translation or AI tools to understand it. I find this process inefficient and repetitive. To address this, I used ChatGPT to create a Chinese translation of the user manual.

I must apologize for not being a professional translator; I had to rely on AI to assist me. However, I believe this is a great first step towards making the manual more accessible to Chinese-speaking users.

Links to the translation:  
- **GitBook:** https://zkl2333.gitbook.io/edgetx-user-manual
- **GitHub:** https://github.com/zkl2333/edgetx-user-manual/tree/2.10/zh-cn

While it’s not perfect, I hope it’s a good starting point. Please consider adding these links to the official manual and using community feedback to improve it further.  

Thank you for your consideration and for all your hard work! 🎉

**Comment by phileville** [comment]
Thank you for the contribution. I have added the link to the published manual.
