### ISSUE TITLE
How-to Recommendation - Disable Touchscreen

### ISSUE THREAD

**Issue by phileville** [EdgeTX/edgetx-user-manual#6]
Although this is pretty simple to do, I see people ask how to do this all the time.  It would be good have a how-to for this.

**Comment by agnauck** [comment]
I can pick up this item. Do you want a google doc upfront, or can I just create a PR with the tutorial?

**Comment by gagarinlg** [comment]
just make a PR

**Comment by agnauck** [comment]
I created a PR.

Still learning the Gitbook app and trying to find the best way for me to contribute, as I was not able to get gitbook running locally on my laptop

**Comment by phileville** [comment]
PR has been merged and user guide has been updated.

**Comment by agnauck** [comment]
its not visible at https://manual.edgetx.org/ yet.
Do we need to cherry pick to other branches as well?

**Comment by phileville** [comment]
Hello Alex,
Yes we need to add it to every version that we want to include it in.  I
have also copied the page over to the 2.10 version manual and it is now
visible.
Thanks again!
Phil
